name: Release to Maven central
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    publish:
      name: Build and deploy to Maven central
      runs-on:
        group: Foxdeli-runners-dind
      permissions:
        contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Setup settings xml with ossrh credentials
          run: |
            cat << EOF > settings.xml
            <?xml version="1.0" encoding="UTF-8"?>
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
            http://maven.apache.org/xsd/settings-1.0.0.xsd">
            
            <servers>
            <server>
            <id>central</id>
            <username>Ue71akLm</username>
            <password>${OSSRH_SETTINGS_XML}</password>
            </server>
            </servers>
            </settings>
            EOF
        - id: install-secret-key
          name: Install gpg secret key
          run: |
            # Install gpg secret key
            cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        - id: publish-to-central
          name: Publish to Central Repository
          run: |
            mvn \
              -s ./settings.xml \
              --no-transfer-progress \
              --batch-mode \
              -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
              clean deploy
        - name: Release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              target/*.jar